config/routes.rb
Rails.application.routes.draw do
  
  get 'recipe_tags/new'
  get 'recipe_tags/create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  root 'static#home'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'signup' => 'users#new'

  get '/users/:user_id/random_recipes' => 'users#random_recipes', :as => 'random_recipes'
  get '/users/:user_id/browse_by_tag' => 'users#browse_by_tag', :as => 'browse_by_tag'
  get '/users/:user_id/browse_by_ingredient' => 'users#browse_by_ingredient', :as => 'browse_by_ingredient'
  get '/users/:user_id' => 'users#show', :as => 'user'


  resources :users, except: :show do
    resources :recipes do
      resources :recipe_tags, only: [:new, :create, :destroy]
    end
    resources :tags, only: :show
    resources :ingredients, only: :show
  end

  resources :tags, only: [:create, :new, :index, :destroy]
  resources :ingredients

  resources :recipe_ingredients, only: [:create, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord

    has_many :recipe_tags, :dependent => :destroy
    has_many :tags, through: :recipe_tags

    has_many :recipe_ingredients, :dependent => :destroy
    has_many :ingredients, through: :recipe_ingredients

    belongs_to :user

    accepts_nested_attributes_for :recipe_ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    before_action :find_user
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
        @recipe = @user.recipes.build
        15.times { @recipe.recipe_ingredients.build }
    end

    def create
        recipe = @user.recipes.build(recipe_params)

        if recipe.save
            flash[:notice] = "Successfully created recipe!"
            redirect_to user_path(@user)
        else
            flash[:alert] = "Sorry, something went wrong"
            render 'new'
        end

    end

    def index
    end

    def edit
        @recipe_ingredients = @recipe.recipe_ingredients
    end

    def update

        if @recipe.update(recipe_params)
            flash[:notice] = "Successfully updated recipe!"
            redirect_to user_recipe_path(@user, @recipe)
        else
            flash[:alert] = "Sorry, something went wrong"
            render 'edit'
        end

    end

    def destroy
        @recipe.destroy
        flash[:notice] = "Recipe deleted"
        redirect_to user_path(@user)
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :description, :instructions, recipe_ingredients_attributes: [:ingredient_id, :magnitude, :unit, :id] )
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: [@user, @recipe], local: true do |recipe_field| %>

    <%= recipe_field.label :name %>
    <%= recipe_field.text_field :name %>
    <br>

    <%= recipe_field.label :description %>
    <%= recipe_field.text_field :description %>
    <br>

    <%= recipe_field.label :instructions %>
    <%= recipe_field.text_area :instructions %>
    <br>

    <h3>Ingredients:</h3>

    <%= recipe_field.fields_for :recipe_ingredients, @recipe.recipe_ingredients do |rec_ing_field| %>    

        <br>
        <%= rec_ing_field.label :ingredient_id, "Ingredient" %>
        <%= rec_ing_field.collection_select :ingredient_id, Ingredient.list_alphabetically, :id, :name  %>
        <%= rec_ing_field.label :magnitude, "Amount"  %>
        <%= rec_ing_field.number_field :magnitude %>
        <%= rec_ing_field.label :unit %>
        <%= rec_ing_field.text_field :unit %>
        

    <% end %>

    


    
    <br>
    <%= recipe_field.submit "Submit Recipe" %>


<% end %>

app/views/recipes/index.html.erb
<h3>Your Recipes:</h3>
<ol>
<% @user.recipes.each do |r| %>
    <li><%= link_to "#{r.name}", user_recipe_path(@user, r) %></li>
<% end %>
</ol>

app/views/recipes/new.html.erb
<%= form_with model: @recipe, local: true, url: user_recipes_path(@user), method: :post do |recipe_field| %>

    <%= recipe_field.label :name %>
    <%= recipe_field.text_field :name %>
    <br>

    <%= recipe_field.label :description %>
    <%= recipe_field.text_field :description %>
    <br>

    <%= recipe_field.label :instructions %>
    <%= recipe_field.text_area :instructions %>
    <br>

    <h3>Ingredients:</h3>

    <%= recipe_field.fields_for :recipe_ingredients do |rec_ing_field| %>    

        <br>
        <%= rec_ing_field.label :ingredient_id, "Ingredient" %>
        <%= rec_ing_field.collection_select :ingredient_id, Ingredient.list_alphabetically, :id, :name  %>
        <%= rec_ing_field.label :magnitude, "Amount"  %>
        <%= rec_ing_field.number_field :magnitude %>
        <%= rec_ing_field.label :unit %>
        <%= rec_ing_field.text_field :unit %>
        

    <% end %>

    


    

    <%= recipe_field.submit "Create Recipe" %>


<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h3>Description:</h3>
<p><%= @recipe.description %></p>

<h3>Ingredients:</h3>
<ul>
<% no_blank_ingredients(@recipe).each do |ing| %>
    <li>
        <%= ing.magnitude %> <%= ing.unit %> <%= ing.ingredient.name %>
    </li>
<% end %>
</ul>

<h3>Instructions:</h3>
<p> <%= @recipe.instructions %> </p>

<h3>Tags:</h3>
<ul>
<% @recipe.tags.each do |tag| %>
    <li>
        <%= link_to "#{tag.name}", user_tag_path(@user, tag) %> <%= button_to "X", user_recipe_recipe_tag_path(@user, @recipe, tag.recipe_tags.find_by(recipe: @recipe)), method: :delete %>
    </li>
<% end %>
</ul>

<%# I probably want to make the delete button for tags easier to read at some point; the path helper taking in an argument with two method calls is a bit ugly %>

<%= link_to "Add a tag!", new_user_recipe_recipe_tag_path(@user, @recipe) %>
<br>

<%= link_to "Edit this recipe", edit_user_recipe_path(@user, @recipe) %>
<br>

<%= button_to "Delete this recipe", user_recipe_path(@user, @recipe), method: :delete %>