config/routes.rb
Rails.application.routes.draw do
  
  get 'recipe_tags/new'
  get 'recipe_tags/create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  root 'static#home'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'signup' => 'users#new'

  get '/users/:user_id/random_recipes' => 'users#random_recipes', :as => 'random_recipes'
  get '/users/:user_id/browse_by_tag' => 'users#browse_by_tag', :as => 'browse_by_tag'
  get '/users/:user_id/browse_by_ingredient' => 'users#browse_by_ingredient', :as => 'browse_by_ingredient'
  get '/users/:user_id' => 'users#show', :as => 'user'


  resources :users, except: :show do
    resources :recipes do
      resources :recipe_tags, only: [:new, :create, :destroy]
    end
    resources :tags, only: :show
    resources :ingredients, only: :show
  end

  resources :tags, only: [:create, :new, :index, :destroy]
  resources :ingredients

  resources :recipe_ingredients, only: [:create, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true
    # validates :email, uniqueness: { message: "Email already taken" }

    has_many :recipes
    has_many :tags, through: :recipes
    has_many :ingredients, through: :recipes

    def self.create_from_omniauth(auth_hash)
        
        @user = User.create do |user|
            user.name = auth_hash[:info][:name]
            user.email = auth_hash[:info][:email]
            user.uid = auth_hash[:uid]
            user.provider = auth_hash[:provider]
            user.password = auth_hash[:credentials][:token]
        end

    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :random_recipes, :browse_by_tag, :browse_by_ingredient]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      # overwrite name if name uniqueness validation triggered so that placeholder can show
      #uniqueness validation changed to email
      @user.email = nil
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  # previous 3 actions only kept in case I want to add full crud to users specifically at some later point

  def show
  end

  def random_recipes
  end

  def browse_by_tag
  end

  def browse_by_ingredient

    if !params[:category].blank?
      @ingredients = @user.ingredients.by_category(params[:category]).list_alphabetically
    else
      @ingredients = @user.ingredients.list_alphabetically.select{|ing| ing.name != "" }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper

    def random_recipes(user, number)
        user.recipes.sample(number)
    end

    def user_ingredients(user)
        ingredients = user.ingredients.list_alphabetically.uniq.drop(1)
        
    end

    def user_tags(user)
        tags = user.tags.list_alphabetically.uniq
    end

    # user_tags and user_ingredients use the list_alphabetically method defined in application_record.rb
    # using drop(1) in user_ingredients removes the blank ingredient but still returns the array, unlike .shift

    def user_recipes(user, object)
        object.recipes.select{|r| r.user == user }
    end

    #user_recipes moved to users_helper.rb to abstract for use with ingredients as well as tags

end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>

<%= f.label :email %>
<%= f.email_field :email, placeholder: "#{@user.errors.messages[:email].first}" %>
<br>
<%= f.label :password %>
<%= f.password_field :password,  placeholder: "#{@user.errors.messages[:password].first}" %>
<br>
<%= f.label :name %>
<%= f.text_field :name, placeholder: "#{@user.errors.messages[:name].first}" %>
<br>
<%= f.submit "Submit" %>

<% end %>

app/views/users/browse_by_ingredient.html.erb
<%= @user.name %> 

<div>
    <h3>Filter By Category:</h3>
    <%= form_tag(browse_by_ingredient_path(@user), method: "get") do %>
        <%= select_tag "category", options_for_select(Ingredient::CATEGORIES) %>
        <%= submit_tag "Filter" %>
    <% end %>

</div>

<h3>Your ingredients:</h3>

<ul>
    <% @ingredients.each do |ingredient| %>
    <%# I have absolutely no idea why, but adding uniq to user_ingredients makes the links appear. Since I wanted to add it anyway, it's no problem, but it is really weird. %>
    <%# The method user.ingredients returns the ingredient from each recipe_ingredient, so there are duplicates. That's why I was going to use uniq anyway. Still very odd %>
    <%# Also, this page and the browse_by_tag page are very similar and could probably be abstracted %>
        <li>
            <%= link_to "#{ingredient.name}", user_ingredient_path(@user, ingredient) %>
        </li>
    <% end %>
</ul>

app/views/users/browse_by_tag.html.erb
<%= @user.name %>

<h3>Your Tags:</h3>

<ul>
    <% user_tags(@user).each do |tag| %>
    <%# I have absolutely no idea why, but adding uniq here makes the links appear. Since I wanted to add it anyway, it's no problem, but it is really weird. %>
    <%# The method user.tags returns the tag from each recipe_tag, so there are duplicates. That's why I was going to use uniq anyway. Still very odd %>
    <%# Also, this page and the browse_by_ingredient page are very similar and could probably be abstracted %>
        <li>
            <%= link_to "#{tag.name}", user_tag_path(@user, tag) %>
        </li>
    <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

<h3>Or <%= button_to "Sign in with Github", '/auth/github', method: 'post' %> </h3>

app/views/users/random_recipes.html.erb
<h1>How about these options?</h1>

<ol>
    <% random_recipes(@user, 3).each do |r| %>
        <li>
            <%= link_to "#{r.name}", user_recipe_path(@user, r) %> 
            <p><%= r.description %></p>
        </li>
    <% end %>
</ol>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>You have <%= @user.recipes.count %> recipes!</h3>
<h1> <%= button_to "See Your Recipes", user_recipes_path(@user), :method => :get %> </h1>

<h3>New Recipe:</h3>
<br>
<%= link_to "Create a new recipe", new_user_recipe_path(@user) %>

<h1>Having trouble deciding what to make for dinner? Try one of these options:</h1>

<%= button_to "See three random recipes!", random_recipes_path(@user), :method => :get %>
<br>
<br>

<%= button_to "Browse by Tag!", browse_by_tag_path(@user), :method => :get %>
<br>
<br>

<%= button_to "Browse by Ingredient!", browse_by_ingredient_path(@user), :method => :get %>