config/routes.rb
Rails.application.routes.draw do
  
  get 'recipe_tags/new'
  get 'recipe_tags/create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  root 'static#home'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'signup' => 'users#new'

  get '/users/:user_id/random_recipes' => 'users#random_recipes', :as => 'random_recipes'
  get '/users/:user_id/browse_by_tag' => 'users#browse_by_tag', :as => 'browse_by_tag'
  get '/users/:user_id/browse_by_ingredient' => 'users#browse_by_ingredient', :as => 'browse_by_ingredient'
  get '/users/:user_id' => 'users#show', :as => 'user'


  resources :users, except: :show do
    resources :recipes do
      resources :recipe_tags, only: [:new, :create, :destroy]
    end
    resources :tags, only: :show
    resources :ingredients, only: :show
  end

  resources :tags, only: [:create, :new, :index, :destroy]
  resources :ingredients

  resources :recipe_ingredients, only: [:create, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

    has_many :recipe_ingredients, :dependent => :destroy
    has_many :recipes, through: :recipe_ingredients

    validates :name, uniqueness: { message: "Ingredient already exists" }

    scope :by_category, -> (category) { where('category == ?', category) }
    scope :no_blanks, -> { where.not('name == ""') }


    CATEGORIES = [
        "",
        "dairy",
        "seasoning",
        "red meat",
        "vegetable",
        "oil",
        "sauce",
        "allium",
        "baking",
        "fowl",
        "fish",
        "noodles",
        "other"
    ]

    

    


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    before_action :find_user, only: :show
    before_action :find_ingredient, only: [:show, :destroy, :edit, :update]

    def show
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)

        if @ingredient.save
            flash[:notice] = "Ingredient successfully created"
            redirect_to new_ingredient_path
        else
            @ingredient.name = nil
            flash[:alert] = "Something went wrong, Ingredient not saved"
            render 'new'
        end
    end

    def index
        if !params[:category].blank?
            @ingredients = Ingredient.by_category(params[:category]).list_alphabetically
        else
            @ingredients = Ingredient.no_blanks.list_alphabetically
        end
    end

    # Ingredient no_blanks scope removes the blank ingredient; this isn't necessary for the by_category scope because the blank ingredient's category is nil

    def destroy
        @ingredient.destroy
        flash[:notice] = "Ingredient deleted"
        redirect_to ingredients_path
    end

    def edit
    end

    def update

        if @ingredient.update(ingredient_params)
            flash[:notice] = "Successfully updated ingredient!"
            redirect_to ingredients_path
        else
            flash[:alert] = "Sorry, something went wrong"
            render 'edit'
        end
    end

    private

    def ingredient_params
        params.require(:ingredient).permit(:name, :category)
    end

    def find_ingredient
        @ingredient = Ingredient.find(params[:id])
    end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with model: @ingredient, local: true do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "#{@ingredient.errors.messages[:name].first}" %>

    <%= f.label :category %>
    <%= f.select :category, Ingredient::CATEGORIES %>

    <%= f.submit"Submit Ingredient" %>
<% end %>

app/views/ingredients/edit.html.erb
<%= render 'form' %>

app/views/ingredients/index.html.erb
<%= link_to "Create a New Ingredient", new_ingredient_path %>

<div>
    <h3>Filter By Category:</h3>
    <%= form_tag(ingredients_path, method: "get") do %>
        <%= select_tag "category", options_for_select(Ingredient::CATEGORIES) %>
        <%= submit_tag "Filter" %>
    <% end %>

</div>

<ul>
<% @ingredients.each do |i| %>
    <li><%= button_to "X", ingredient_path(i), method: :delete %> <span><%= i.name %></span> used in <%= i.recipes.count %> recipes <span>category:</span> <%= i.category %> </li> 
    <%= link_to "Edit this ingredient", edit_ingredient_path(i) %>
    <br>
    <%end%>
</ul>

app/views/ingredients/new.html.erb
<%= form_with model: @ingredient, local: true do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "#{@ingredient.errors.messages[:name].first}" %>

    <%= f.submit"Create New Ingredient" %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %> Recipes:</h1>

<ol>
    <% user_recipes(@user, @ingredient).each do |r| %>
        <li><%= link_to "#{r.name}", user_recipe_path(@user, r) %>, <%= r.description %> </li>
    <% end %>
</ol>