config/routes.rb
Rails.application.routes.draw do
  
  get 'recipe_tags/new'
  get 'recipe_tags/create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  root 'static#home'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'signup' => 'users#new'

  get '/users/:user_id/random_recipes' => 'users#random_recipes', :as => 'random_recipes'
  get '/users/:user_id/browse_by_tag' => 'users#browse_by_tag', :as => 'browse_by_tag'
  get '/users/:user_id/browse_by_ingredient' => 'users#browse_by_ingredient', :as => 'browse_by_ingredient'
  get '/users/:user_id' => 'users#show', :as => 'user'


  resources :users, except: :show do
    resources :recipes do
      resources :recipe_tags, only: [:new, :create, :destroy]
    end
    resources :tags, only: :show
    resources :ingredients, only: :show
  end

  resources :tags, only: [:create, :new, :index, :destroy]
  resources :ingredients

  resources :recipe_ingredients, only: [:create, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :recipe_tags, :dependent => :destroy
    has_many :recipes, through: :recipe_tags

    validates :name, uniqueness: { message: "Tag already exists" }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController


    before_action :find_user, only: :show
    before_action :find_tag, only: [:show, :destroy]

    def show
    end

    def new
        @tag = Tag.new
    end

    def create
        @tag = Tag.new(tag_params)

        if @tag.save
            flash[:notice] = "Tag successfully created"
            redirect_to new_tag_path
        else
            @tag.name = nil
            flash[:alert] = "Something went wrong, tag not saved"
            render 'new'
        end
    end

    def index
        @tags = Tag.list_alphabetically
    end

    def destroy
        @tag.destroy
        flash[:notice] = "Tag deleted"
        redirect_to tags_path
    end

    private

    def tag_params
        params.require(:tag).permit(:name)
    end

    def find_tag
        @tag = Tag.find(params[:id])
    end

end
 

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<%= link_to "Create a New Tag", new_tag_path %>

<ul>
<% @tags.each do |t| %>
    <li><%= button_to "X", tag_path(t), method: :delete %><%= t.name %></li> 
<%end%>
</ul>

app/views/tags/new.html.erb
<%= form_with model: @tag, local: true do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "#{@tag.errors.messages[:name].first}" %>

    <%= f.submit"Create New Tag" %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %> Recipes:</h1>

<ol>
    <% user_recipes(@user, @tag).each do |r| %>
        <li><%= link_to "#{r.name}", user_recipe_path(@user, r) %>, <%= r.description %> </li>
    <% end %>
</ol>